services:
  - type: web
    name: rivero-web-base
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ACCESS_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false