const express=require("express");
const controller=require("../controllers/room.controller");
const router=express.Router();
router.post("/rooms/create",controller.create);
router.post("/rooms/join",controller.join);
router.get("/rooms/state",controller.state);
router.post("/rooms/leave",controller.leave);
router.post("/rooms/game/start",controller.startGame);
router.get("/rooms/game/state",controller.gameState);
router.post("/rooms/game/answer",controller.answerGame);
router.post("/rooms/game/next",controller.nextRound);
module.exports=router;
