const crypto = require("crypto");
const gameService = require("./game.service");
const rooms = new Map();
const playerRooms = new Map();
const ROOM_TTL_MS = 60 * 60 * 1000;
const MAX_PLAYERS = 2;
const ROUND_TIME_MS = 20000;
const AVATARS = ["🧑","👩","👨","🧑‍💻","👩‍💻","👨‍💻","🦊","🐼","🐱","🐸","🐵","🐨"];
function clean(value, fallback) { return String(value || fallback).trim().replace(/[<>]/g, "").slice(0, 18) || fallback; }
function avatar(value) { return AVATARS.includes(value) ? value : AVATARS[0]; }
function code() { let c; do c = String(Math.floor(1000 + Math.random() * 9000)); while (rooms.has(c)); return c; }
function cleanup() { const now = Date.now(); for (const [c, room] of rooms) if (now - room.updatedAt > ROOM_TTL_MS) { room.players.forEach(p => playerRooms.delete(p.id)); rooms.delete(c); } }
function publicRoom(room, playerId) { return { code: room.code, status: room.players.length === 2 ? "ready" : "waiting", players: room.players.map(p => ({ id: p.id, nickname: p.nickname, avatar: p.avatar, ready: p.id === playerId || p.ready, score: p.score || 0 })), hostId: room.hostId, game: room.game ? { status: room.game.status, round: room.game.round, endsAt: room.game.endsAt } : null }; }
function createPlayer(nickname, avatarChoice) { return { id: crypto.randomUUID(), nickname: clean(nickname, "Jugador"), avatar: avatar(avatarChoice), ready: false, score: 0, streak: 0, joinedAt: Date.now() }; }
function create(nickname, avatarChoice) { cleanup(); const player = createPlayer(nickname, avatarChoice); const room = { code: code(), hostId: player.id, players: [player], createdAt: Date.now(), updatedAt: Date.now(), game: null }; rooms.set(room.code, room); playerRooms.set(player.id, room.code); return { playerId: player.id, room: publicRoom(room, player.id) }; }
function join(roomCode, nickname, avatarChoice) { cleanup(); const room = rooms.get(String(roomCode).trim()); if (!room) throw Object.assign(new Error("No existe una sala con ese código."), { status: 404 }); if (room.players.length >= MAX_PLAYERS) throw Object.assign(new Error("La sala ya está llena."), { status: 409 }); const player = createPlayer(nickname, avatarChoice); room.players.push(player); room.updatedAt = Date.now(); playerRooms.set(player.id, room.code); return { playerId: player.id, room: publicRoom(room, player.id) }; }
function roomFor(playerId) { cleanup(); const room = rooms.get(playerRooms.get(playerId)); if (!room) throw Object.assign(new Error("La sala ya no existe."), { status: 404 }); room.updatedAt = Date.now(); return room; }
function get(playerId) { return publicRoom(roomFor(playerId), playerId); }
function getByCode(roomCode) { cleanup(); const room = rooms.get(String(roomCode || "").trim()); if (!room) throw Object.assign(new Error("La sala ya no existe."), { status: 404 }); return publicRoom(room); }
function leave(playerId) { const code = playerRooms.get(playerId), room = rooms.get(code); if (!room) return; room.players = room.players.filter(p => p.id !== playerId); playerRooms.delete(playerId); room.updatedAt = Date.now(); if (!room.players.length) rooms.delete(code); else room.hostId = room.players[0].id; }
function leaveByCode(roomCode) { const room = rooms.get(String(roomCode || "").trim()); if (!room) return; room.players.forEach(p => playerRooms.delete(p.id)); rooms.delete(room.code); }
function playerInRoom(playerId) { const code = playerRooms.get(playerId); return code ? rooms.get(code) : null; }
async function startGame(playerId) { const room = roomFor(playerId); if (room.players.length !== 2) throw Object.assign(new Error("Esperando al segundo jugador."), { status: 409 }); if (room.game?.status === "playing" || room.game?.status === "round_end") return publicGame(room, playerId); const challenge = await gameService.createChallenge(); room.players.forEach(p => { p.score = 0; p.streak = 0; }); room.game = { id: crypto.randomUUID(), round: 1, status: "playing", challenge, startedAt: Date.now(), endsAt: Date.now() + ROUND_TIME_MS, answers: {}, winner: null }; room.updatedAt = Date.now(); return publicGame(room, playerId); }
function finishRound(room) { const g = room.game; if (!g || g.status !== "playing") return; g.status = "round_end"; if (!g.winner) { const entries = Object.entries(g.answers).filter(([,a]) => a.correct); if (entries.length) { entries.sort((a,b) => a[1].answeredAt - b[1].answeredAt); g.winner = entries[0][0]; } } }
function publicGame(room, playerId) { const g = room.game; if (!g) return { status: "waiting", players: publicRoom(room, playerId).players }; if (g.status === "playing" && Date.now() >= g.endsAt) finishRound(room); const p = room.players.find(x => x.id === playerId); return { status: g.status, round: g.round, endsAt: g.endsAt, serverNow: Date.now(), ...gameService.publicChallenge(g.challenge), score: p?.score || 0, streak: p?.streak || 0, players: room.players.map(x => ({ nickname: x.nickname, avatar: x.avatar, score: x.score || 0, answered: !!g.answers[x.id] })), winner: g.winner, myAnswer: g.answers[playerId] || null, correctAnswer: g.status === "round_end" ? g.challenge.answer : undefined }; }
async function answerGame(playerId, answer) { const room = roomFor(playerId), g = room.game; if (!g || g.status !== "playing") throw Object.assign(new Error("La ronda no está activa."), { status: 409 }); if (Date.now() >= g.endsAt) { finishRound(room); throw Object.assign(new Error("Se acabó el tiempo."), { status: 409 }); } if (g.answers[playerId]) throw Object.assign(new Error("Ya respondiste esta ronda."), { status: 409 }); const player = room.players.find(p => p.id === playerId); const correct = gameService.scoreAnswer(g.challenge, answer); const points = correct ? (g.challenge.type === "date" ? 15 : 10) : 0; if (correct) { player.score += points; player.streak += 1; } else player.streak = 0; g.answers[playerId] = { correct, answeredAt: Date.now(), points }; if (correct && !g.winner) g.winner = playerId; if (Object.keys(g.answers).length === room.players.length) finishRound(room); room.updatedAt = Date.now(); return publicGame(room, playerId); }
async function nextRound(playerId) { const room = roomFor(playerId), g = room.game; if (!g || g.status !== "round_end") throw Object.assign(new Error("La ronda todavía no terminó."), { status: 409 }); if (room.hostId !== playerId) throw Object.assign(new Error("Solo el creador puede iniciar la siguiente ronda."), { status: 403 }); g.round += 1; g.challenge = await gameService.createChallenge(); g.answers = {}; g.winner = null; g.status = "playing"; g.startedAt = Date.now(); g.endsAt = Date.now() + ROUND_TIME_MS; room.updatedAt = Date.now(); return publicGame(room, playerId); }
module.exports = { AVATARS, create, join, get, getByCode, leave, leaveByCode, playerInRoom, publicRoom, startGame, answerGame, nextRound, publicGame };
